# SwiftLint configuration (shared-kit)

disabled_rules:
  - todo
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - force_cast
  - force_try
  - inclusive_language
  - function_parameter_count
  - shorthand_operator
  - identifier_name
  - trailing_comma
  - opening_brace
  - type_name
  - nesting
  - for_where
  - closure_parameter_position
  - colon
  - multiple_closures_with_trailing_closure
  - array_init
  - large_tuple
  - redundant_sendable
  - unused_optional_binding
  - orphaned_doc_comment
  - trailing_whitespace
  - unneeded_override

opt_in_rules:
  - array_init
  - closure_end_indentation
  - explicit_init
  - modifier_order
  - redundant_nil_coalescing

included:
  - .

excluded:
  - "**/.build"
  - "**/DerivedData"
  - "**/.swiftpm"
  - "**/Pods"
  - "**/Carthage"
  - "**/node_modules"
  - "**/*.generated.swift"
  - "Tools/Automation"
  - "**/Automation/**"
  - "**/automation/**"
  - "**/Generated/**"

identifier_name:
  min_length: { warning: 1, error: 1 }
  validates_start_with_lowercase: true
  allowed_characters: "a-zA-Z0-9_"
  excluded: [i, j, id, x, y, z, a, b, r, g, t, l, n]

line_length: { warning: 200, error: 240 }
reporter: xcode
