# Unified SwiftLint Configuration
# Source: shared-kit/.swiftlint.yml
# Version: 1.0.0

disabled_rules:
  - todo
  - function_body_length
  - type_body_length
  - file_length
  - sorted_imports
  - inclusive_language
  - trailing_comma
  - opening_brace
  - identifier_name
  - redundant_discardable_let

opt_in_rules:
  - array_init
  - closure_end_indentation
  - explicit_init
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - trailing_whitespace
  - modifier_order
  - redundant_nil_coalescing

modifier_order:
  preferred_modifier_order:
    [
      acl,
      isolation,
      setterACL,
      dynamic,
      mutators,
      lazy,
      final,
      required,
      convenience,
      typeMethods,
      owned,
    ]

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

force_cast: warning
force_try: warning

line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: false
  ignores_comments: true

included:
  - .

excluded:
  - "**/.build"
  - "**/DerivedData"
  - "**/.swiftpm"
  - "**/Pods"
  - "**/Carthage"
  - "**/node_modules"
  - "**/*.generated.swift"
  - "**/Generated/**"
  - "**/Tests/**"
  - "fastlane"
  - "docs"

reporter: xcode
